services:
  mysql8:
    image: mysql:8.0.28
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
#       将本地的mysql文件夹挂载到容器的/docker-entrypoint-initdb.d/文件夹中
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"